# coding: utf-8
"""
conftest.py — Pytest fixtures for cyber-astrology test suite.
Provides a frozen natal chart fixture for offline, deterministic testing.
"""

import pytest


@pytest.fixture
def known_chart_data():
    """
    Frozen sample natal chart for:
      Date: 1990-06-15
      Time: 14:30
      Location: São Paulo, Brazil (-23.5505, -46.6333, America/Sao_Paulo)
    Contains exact planetary coordinates, signs, and house cusps.
    Runs 100% offline without any network or geocoding calls.
    """
    return {
        "name": "Test Subject",
        "planets": {
            "sun": {
                "longitude": 84.3484,
                "degree_in_sign": 24.3484,
                "sign_abbr": "Gem",
                "sign_pt": "Gêmeos",
                "sign_key": "gemini",
                "house": 8,
                "retrograde": False,
                "name_pt": "Sol",
                "name_en": "Sun",
                "symbol": "☉",
                "key": "sun",
            },
            "moon": {
                "longitude": 348.4296,
                "degree_in_sign": 18.4296,
                "sign_abbr": "Pis",
                "sign_pt": "Peixes",
                "sign_key": "pisces",
                "house": 5,
                "retrograde": False,
                "name_pt": "Lua",
                "name_en": "Moon",
                "symbol": "☽",
                "key": "moon",
            },
            "mercury": {
                "longitude": 66.0851,
                "degree_in_sign": 6.0851,
                "sign_abbr": "Gem",
                "sign_pt": "Gêmeos",
                "sign_key": "gemini",
                "house": 8,
                "retrograde": False,
                "name_pt": "Mercúrio",
                "name_en": "Mercury",
                "symbol": "☿",
                "key": "mercury",
            },
            "venus": {
                "longitude": 49.0471,
                "degree_in_sign": 19.0471,
                "sign_abbr": "Tau",
                "sign_pt": "Touro",
                "sign_key": "taurus",
                "house": 7,
                "retrograde": False,
                "name_pt": "Vênus",
                "name_en": "Venus",
                "symbol": "♀",
                "key": "venus",
            },
            "mars": {
                "longitude": 11.2060,
                "degree_in_sign": 11.2060,
                "sign_abbr": "Ari",
                "sign_pt": "Áries",
                "sign_key": "aries",
                "house": 5,
                "retrograde": False,
                "name_pt": "Marte",
                "name_en": "Mars",
                "symbol": "♂",
                "key": "mars",
            },
            "jupiter": {
                "longitude": 105.9391,
                "degree_in_sign": 15.9391,
                "sign_abbr": "Can",
                "sign_pt": "Câncer",
                "sign_key": "cancer",
                "house": 9,
                "retrograde": False,
                "name_pt": "Júpiter",
                "name_en": "Jupiter",
                "symbol": "♃",
                "key": "jupiter",
            },
            "saturn": {
                "longitude": 294.0185,
                "degree_in_sign": 24.0185,
                "sign_abbr": "Cap",
                "sign_pt": "Capricórnio",
                "sign_key": "capricorn",
                "house": 3,
                "retrograde": True,
                "name_pt": "Saturno",
                "name_en": "Saturn",
                "symbol": "♄",
                "key": "saturn",
            },
            "uranus": {
                "longitude": 278.1563,
                "degree_in_sign": 8.1563,
                "sign_abbr": "Cap",
                "sign_pt": "Capricórnio",
                "sign_key": "capricorn",
                "house": 3,
                "retrograde": True,
                "name_pt": "Urano",
                "name_en": "Uranus",
                "symbol": "♅",
                "key": "uranus",
            },
            "neptune": {
                "longitude": 283.7113,
                "degree_in_sign": 13.7113,
                "sign_abbr": "Cap",
                "sign_pt": "Capricórnio",
                "sign_key": "capricorn",
                "house": 3,
                "retrograde": True,
                "name_pt": "Netuno",
                "name_en": "Neptune",
                "symbol": "♆",
                "key": "neptune",
            },
            "pluto": {
                "longitude": 225.3969,
                "degree_in_sign": 15.3969,
                "sign_abbr": "Sco",
                "sign_pt": "Escorpião",
                "sign_key": "scorpio",
                "house": 1,
                "retrograde": True,
                "name_pt": "Plutão",
                "name_en": "Pluto",
                "symbol": "♇",
                "key": "pluto",
            },
        },
        "ascendant": {
            "longitude": 218.3542,
            "degree_in_sign": 8.3542,
            "sign_abbr": "Sco",
            "sign_pt": "Escorpião",
            "sign_key": "scorpio",
            "name_pt": "Ascendente",
            "name_en": "Ascendant",
            "symbol": "AC",
            "key": "ascendant",
            "house": 1,
            "retrograde": False,
        },
        "mc": {
            "longitude": 134.1200,
            "degree_in_sign": 14.1200,
            "sign_abbr": "Leo",
            "sign_pt": "Leão",
            "sign_key": "leo",
            "name_pt": "Meio do Céu",
            "name_en": "Midheaven",
            "symbol": "MC",
            "key": "mc",
            "house": 10,
            "retrograde": False,
        },
        "house_cusps": [
            218.35, 248.50, 280.10, 314.12, 345.80, 14.20,
            38.35, 68.50, 100.10, 134.12, 165.80, 194.20,
        ],
    }
